// Curated ~100 real Ghanaian-market products mapped onto the app's 3-level taxonomy.
// Prices are realistic GHS street/retail prices (2026). Images fetched per `keyword`.
export type SeedProduct = {
  name: string;
  brand: string;
  price: number;
  main: string;
  sub: string;
  sub2: string;
  city: string;
  region: string;
  keyword: string;
  sizes?: number[];
  condition?: string;
  negotiable: boolean;
  delivery: boolean;
  desc: string;
};

const A = "Accra";
const AR = "Greater Accra";
const K = "Kumasi";
const KAR = "Ashanti";
const T = "Tamale";
const TR = "Northern";
const CC = "Cape Coast";
const CR = "Central";

export const PRODUCTS: SeedProduct[] = [
  // ── Phones & Tablets ──────────────────────────────────────
  { name: "iPhone 13 Pro 256GB", brand: "Apple", price: 12500, main: "Phones & Tablets", sub: "Mobile Phones", sub2: "Smartphones", city: A, region: AR, keyword: "iphone", negotiable: true, delivery: true, condition: "Used - Like New", desc: "Apple iPhone 13 Pro 256GB. Factory unlocked, battery health 92%. Comes with box and charger." },
  { name: "Samsung Galaxy S24 Ultra 256GB", brand: "Samsung", price: 19000, main: "Phones & Tablets", sub: "Mobile Phones", sub2: "Smartphones", city: A, region: AR, keyword: "samsung galaxy", negotiable: true, delivery: true, condition: "Brand New", desc: "Samsung Galaxy S24 Ultra 256GB with S-Pen. Sealed, Ghana warranty." },
  { name: "Tecno Camon 30 8/256GB", brand: "Tecno", price: 3200, main: "Phones & Tablets", sub: "Mobile Phones", sub2: "Android Phones", city: A, region: AR, keyword: "smartphone", negotiable: true, delivery: true, condition: "Brand New", desc: "Tecno Camon 30 with 50MP camera. Dual SIM, big battery. 12 months warranty." },
  { name: "Infinix Hot 40i 4/128GB", brand: "Infinix", price: 1850, main: "Phones & Tablets", sub: "Mobile Phones", sub2: "Android Phones", city: K, region: KAR, keyword: "android phone", negotiable: true, delivery: true, condition: "Brand New", desc: "Infinix Hot 40i 4GB RAM 128GB storage. Brand new in box with 12-month warranty." },
  { name: "Itel A70 3/64GB", brand: "Itel", price: 1150, main: "Phones & Tablets", sub: "Mobile Phones", sub2: "Basic & Feature Phones", city: A, region: AR, keyword: "mobile phone", negotiable: true, delivery: true, condition: "Brand New", desc: "Itel A70 with 6.6-inch screen. Affordable daily driver. Sealed pack." },
  { name: "Nokia 105 Single SIM", brand: "Nokia", price: 380, main: "Phones & Tablets", sub: "Mobile Phones", sub2: "Basic & Feature Phones", city: K, region: KAR, keyword: "nokia 105", negotiable: false, delivery: true, condition: "Brand New", desc: "Nokia 105 feature phone with torch. 1-month battery standby." },
  { name: "Samsung Galaxy Tab A9+ 128GB", brand: "Samsung", price: 4500, main: "Phones & Tablets", sub: "Tablets", sub2: "Android Tablets", city: A, region: AR, keyword: "samsung tablet", negotiable: true, delivery: true, condition: "Brand New", desc: "Samsung Galaxy Tab A9+ 11-inch 128GB. Ideal for school and streaming." },
  { name: "Anker 20000mAh Power Bank", brand: "Anker", price: 700, main: "Phones & Tablets", sub: "Phone Accessories", sub2: "Power Banks", city: A, region: AR, keyword: "power bank", negotiable: true, delivery: true, condition: "Brand New", desc: "Anker 20000mAh dual USB power bank. Fast charging. Original quality." },
  { name: "Apple AirPods Pro 2", brand: "Apple", price: 3500, main: "Phones & Tablets", sub: "Phone Accessories", sub2: "Earbuds & Headsets", city: A, region: AR, keyword: "airpods", negotiable: true, delivery: true, condition: "Brand New", desc: "Apple AirPods Pro 2 with Active Noise Cancellation. Sealed." },
  { name: "Samsung Galaxy Buds2", brand: "Samsung", price: 950, main: "Phones & Tablets", sub: "Phone Accessories", sub2: "Earbuds & Headsets", city: K, region: KAR, keyword: "wireless earbuds", negotiable: true, delivery: true, condition: "Brand New", desc: "Samsung Galaxy Buds2 wireless earbuds with charging case." },

  // ── Electronics ───────────────────────────────────────────
  { name: "LG 43-inch 4K Smart TV", brand: "LG", price: 7200, main: "Electronics", sub: "TVs & Video", sub2: "Smart TVs", city: A, region: AR, keyword: "lg smart tv", negotiable: true, delivery: true, condition: "Brand New", desc: "LG 43-inch 4K UHD Smart TV with webOS. Full Ghana warranty." },
  { name: "Hisense 32-inch HD TV", brand: "Hisense", price: 3600, main: "Electronics", sub: "TVs & Video", sub2: "LED & LCD TVs", city: A, region: AR, keyword: "led television", negotiable: true, delivery: true, condition: "Brand New", desc: "Hisense 32-inch HD LED TV. Affordable for the family living room." },
  { name: "JBL Flip 6 Bluetooth Speaker", brand: "JBL", price: 1550, main: "Electronics", sub: "Audio & Speakers", sub2: "Bluetooth Speakers", city: A, region: AR, keyword: "bluetooth speaker", negotiable: true, delivery: true, condition: "Brand New", desc: "JBL Flip 6 portable speaker. Waterproof, 12-hour playtime." },
  { name: "Sony WH-CH520 Headphones", brand: "Sony", price: 800, main: "Electronics", sub: "Audio & Speakers", sub2: "Headphones & Earphones", city: A, region: AR, keyword: "headphones", negotiable: true, delivery: true, condition: "Brand New", desc: "Sony WH-CH520 wireless on-ear headphones with 50h battery." },
  { name: "Canon EOS 1500D DSLR", brand: "Canon", price: 8200, main: "Electronics", sub: "Cameras & Drones", sub2: "DSLR & Mirrorless", city: A, region: AR, keyword: "dslr camera", negotiable: true, delivery: true, condition: "Used - Good", desc: "Canon EOS 1500D with 18-55mm kit lens. Great for events and portraits." },
  { name: "PlayStation 5 Slim", brand: "Sony", price: 8500, main: "Electronics", sub: "Gaming", sub2: "Consoles", city: A, region: AR, keyword: "playstation 5", negotiable: true, delivery: true, condition: "Brand New", desc: "PlayStation 5 Slim with DualSense controller. Sealed, regional warranty." },
  { name: "Apple MacBook Air M2 8/256GB", brand: "Apple", price: 24500, main: "Electronics", sub: "Computers & Laptops", sub2: "Laptops", city: A, region: AR, keyword: "macbook air", negotiable: true, delivery: true, condition: "Brand New", desc: "MacBook Air M2 13-inch. Lightweight, all-day battery." },
  { name: "HP EliteBook 840 G6 (Refurbished)", brand: "HP", price: 9800, main: "Electronics", sub: "Computers & Laptops", sub2: "Refurbished & Used", city: A, region: AR, keyword: "laptop computer", negotiable: true, delivery: true, condition: "Used - Like New", desc: "HP EliteBook 840 G6 i5 8th gen, 16GB RAM, 256GB SSD. 6-month warranty." },
  { name: "TP-Link Archer C6 Router", brand: "TP-Link", price: 750, main: "Electronics", sub: "Networking & Smart Home", sub2: "Routers & Modems", city: A, region: AR, keyword: "wifi router", negotiable: true, delivery: true, condition: "Brand New", desc: "TP-Link Archer C6 dual-band AC1200 router. Covers a 3-bedroom house." },
  { name: "Hikvision 4-Camera CCTV Kit", brand: "Hikvision", price: 3900, main: "Electronics", sub: "Networking & Smart Home", sub2: "Security Cameras & CCTV", city: A, region: AR, keyword: "cctv camera", negotiable: true, delivery: true, condition: "Brand New", desc: "Hikvision 4-camera 1TB DVR CCTV kit. Installation support available." },

  // ── Fashion ───────────────────────────────────────────────
  { name: "GH Wax Print Fabric (6 yards)", brand: "Ghana Textiles", price: 350, main: "Fashion", sub: "Traditional & Cultural Wear", sub2: "Kente & Prints", city: A, region: AR, keyword: "african wax print fabric", negotiable: true, delivery: true, condition: "Brand New", desc: "Genuine GH wax print, 6 yards. Perfect for dresses, shirts and boubous." },
  { name: "Handwoven Kente Stole", brand: "Local Weaver", price: 300, main: "Fashion", sub: "Traditional & Cultural Wear", sub2: "Kente & Prints", city: K, region: KAR, keyword: "kente cloth", negotiable: true, delivery: true, condition: "Brand New", desc: "Authentic handwoven kente stole from Bonwire. Great for events and office." },
  { name: "Ashanti Smock (Fugu)", brand: "Local Tailor", price: 450, main: "Fashion", sub: "Traditional & Cultural Wear", sub2: "Dashiki & Shirts", city: K, region: KAR, keyword: "traditional african clothing", negotiable: true, delivery: true, condition: "Brand New", desc: "Classic Ashanti smock, tailor-made to your size. Worn at ceremonial events." },
  { name: "Ankara A-Line Dress", brand: "Local Designer", price: 250, main: "Fashion", sub: "Women's Clothing", sub2: "Dresses & Jumpsuits", city: A, region: AR, keyword: "african print dress", negotiable: true, delivery: true, condition: "Brand New", desc: "Tailored Ankara A-line dress. Beautiful for church and outings." },
  { name: "Men's Kente Shirt", brand: "Local Tailor", price: 280, main: "Fashion", sub: "Men's Clothing", sub2: "Shirts", city: K, region: KAR, keyword: "kente shirt", negotiable: true, delivery: true, condition: "Brand New", desc: "Hand-sewn kente shirt. Fits true to size, breathable fabric." },
  { name: "Nike Air Force 1", brand: "Nike", price: 2600, main: "Fashion", sub: "Footwear", sub2: "Sneakers & Trainers", city: A, region: AR, keyword: "nike air force", negotiable: true, delivery: true, sizes: [40, 41, 42, 43, 44], condition: "Brand New", desc: "Original Nike Air Force 1. Sizes 40-44 available." },
  { name: "Adidas Campus 00s", brand: "Adidas", price: 1900, main: "Fashion", sub: "Footwear", sub2: "Men's Shoes", city: A, region: AR, keyword: "adidas sneakers", negotiable: true, delivery: true, sizes: [39, 40, 41, 42, 43], condition: "Brand New", desc: "Original Adidas Campus 00s. Classic everyday sneaker." },
  { name: "Handmade Leather Sandals", brand: "Local Cobbler", price: 150, main: "Fashion", sub: "Footwear", sub2: "Sandals & Slippers", city: K, region: KAR, keyword: "leather sandals", negotiable: true, delivery: true, sizes: [40, 41, 42, 43], condition: "Brand New", desc: "Handmade leather sandals from Kumasi craftsmen. Durable and stylish." },
  { name: "Designer Leather Handbag", brand: "Local Brand", price: 550, main: "Fashion", sub: "Bags & Luggage", sub2: "Handbags", city: A, region: AR, keyword: "leather handbag", negotiable: true, delivery: true, condition: "Brand New", desc: "Genuine leather handbag with compartments. Ideal gift for ladies." },
  { name: "Beaded Necklace Set", brand: "Local Artisan", price: 180, main: "Fashion", sub: "Jewellery & Watches", sub2: "Necklaces & Pendants", city: A, region: AR, keyword: "beaded necklace", negotiable: true, delivery: true, condition: "Brand New", desc: "Handcrafted beaded necklace set. Colourful and made to last." },
  { name: "Casio Men's Wrist Watch", brand: "Casio", price: 700, main: "Fashion", sub: "Jewellery & Watches", sub2: "Watches", city: A, region: AR, keyword: "wrist watch", negotiable: true, delivery: true, condition: "Brand New", desc: "Casio analog watch with leather strap. Water resistant." },
  { name: "Ray-Ban Sunglasses", brand: "Ray-Ban", price: 850, main: "Fashion", sub: "Accessories", sub2: "Sunglasses & Eyewear", city: A, region: AR, keyword: "sunglasses", negotiable: true, delivery: true, condition: "Brand New", desc: "Ray-Ban aviator sunglasses with UV protection and case." },

  // ── Health & Beauty ───────────────────────────────────────
  { name: "Pure Shea Butter (1kg)", brand: "Local Producer", price: 120, main: "Health & Beauty", sub: "Skin Care", sub2: "Moisturizers & Creams", city: T, region: TR, keyword: "shea butter", negotiable: true, delivery: true, condition: "Brand New", desc: "Unrefined shea butter from Tamale. Great for skin and hair." },
  { name: "Alata Samina Black Soap", brand: "Local Producer", price: 80, main: "Health & Beauty", sub: "Bath & Body", sub2: "Bar Soaps", city: K, region: KAR, keyword: "black soap", negotiable: true, delivery: true, condition: "Brand New", desc: "Traditional African black soap. Clears blemishes and softens skin." },
  { name: "13x6 HD Lace Frontal", brand: "Local Supplier", price: 350, main: "Health & Beauty", sub: "Hair Care & Wigs", sub2: "Wigs & Extensions", city: A, region: AR, keyword: "hair weave", negotiable: true, delivery: true, condition: "Brand New", desc: "13x6 HD lace frontal, pre-plucked. 180% density, ready to install." },
  { name: "Virgin Coconut Oil 500ml", brand: "Local Producer", price: 90, main: "Health & Beauty", sub: "Bath & Body", sub2: "Body Lotion & Oil", city: CC, region: CR, keyword: "coconut oil", negotiable: true, delivery: true, condition: "Brand New", desc: "Cold-pressed virgin coconut oil from the Central Region." },
  { name: "Men's Eau de Toilette 100ml", brand: "Aramis", price: 600, main: "Health & Beauty", sub: "Fragrances & Perfumes", sub2: "Men's Fragrances", city: A, region: AR, keyword: "perfume bottle", negotiable: true, delivery: true, condition: "Brand New", desc: "Aramis classic men's fragrance. Sealed box, original import." },
  { name: "Wahl Hair Clipper Kit", brand: "Wahl", price: 350, main: "Health & Beauty", sub: "Men's Grooming", sub2: "Trimmers & Clippers", city: A, region: AR, keyword: "hair clipper", negotiable: true, delivery: true, condition: "Brand New", desc: "Wahl professional hair clipper with attachment guards." },
  { name: "Omron Blood Pressure Monitor", brand: "Omron", price: 950, main: "Health & Beauty", sub: "Health Care & Wellness", sub2: "Medical Equipment & Monitors", city: A, region: AR, keyword: "blood pressure monitor", negotiable: false, delivery: true, condition: "Brand New", desc: "Omron automatic BP monitor with cuff. Reliable readings." },
  { name: "Vitamin C 1000mg (90 tabs)", brand: "Local Pharmacy", price: 150, main: "Health & Beauty", sub: "Vitamins & Supplements", sub2: "Vitamins & Minerals", city: A, region: AR, keyword: "vitamin c", negotiable: false, delivery: true, condition: "Brand New", desc: "Vitamin C 1000mg immune support. Food and Drugs registered." },

  // ── Home & Garden ─────────────────────────────────────────
  { name: "Spring Mattress (King Size)", brand: "Vono", price: 2400, main: "Home & Garden", sub: "Furniture", sub2: "Mattresses & Bedding Bases", city: A, region: AR, keyword: "mattress", negotiable: true, delivery: true, condition: "Brand New", desc: "Vono king-size spring mattress. 10-year warranty." },
  { name: "4-Burner Gas Cooker", brand: "Local Brand", price: 3800, main: "Home & Garden", sub: "Kitchen & Dining", sub2: "Cookware & Pots", city: A, region: AR, keyword: "gas cooker", negotiable: true, delivery: true, condition: "Brand New", desc: "4-burner gas cooker with grill and oven. Stainless steel top." },
  { name: "Double-Door Refrigerator 480L", brand: "LG", price: 9500, main: "Home & Garden", sub: "Appliances", sub2: "Refrigerators & Freezers", city: A, region: AR, keyword: "refrigerator", negotiable: true, delivery: true, condition: "Brand New", desc: "LG double-door fridge with inverter compressor. Energy efficient." },
  { name: "Hisense Washing Machine 9kg", brand: "Hisense", price: 6800, main: "Home & Garden", sub: "Appliances", sub2: "Washing Machines", city: A, region: AR, keyword: "washing machine", negotiable: true, delivery: true, condition: "Brand New", desc: "Hisense 9kg front-load washer. Multiple wash programmes." },
  { name: "Standing Fan 18-inch", brand: "Binatone", price: 850, main: "Home & Garden", sub: "Appliances", sub2: "Fans & Air Purifiers", city: A, region: AR, keyword: "electric fan", negotiable: true, delivery: true, condition: "Brand New", desc: "Binatone 18-inch standing fan with remote and 3 speeds." },
  { name: "Bed Sheet Set (Queen)", brand: "Local Brand", price: 300, main: "Home & Garden", sub: "Bedding & Bath", sub2: "Bed Sheets & Covers", city: A, region: AR, keyword: "bed sheets", negotiable: true, delivery: true, condition: "Brand New", desc: "4-piece queen bed sheet set. Soft cotton, several colours." },
  { name: "Dangote Cement 50kg", brand: "Dangote", price: 100, main: "Home & Garden", sub: "Tools & Home Improvement", sub2: "Hardware & Fasteners", city: A, region: AR, keyword: "cement bags", negotiable: false, delivery: true, condition: "Brand New", desc: "Dangote 42.5R cement, 50kg bag. Fresh stock, nationwide delivery." },
  { name: "Water Storage Tank 1000L", brand: "Local Brand", price: 2200, main: "Home & Garden", sub: "Garden & Outdoor", sub2: "Storage & Sheds", city: A, region: AR, keyword: "water tank", negotiable: true, delivery: true, condition: "Brand New", desc: "UV-stabilised 1000L water tank. Ideal for water storage." },
  { name: "Solar Panel 300W", brand: "Local Supplier", price: 2800, main: "Home & Garden", sub: "Tools & Home Improvement", sub2: "Electrical Supplies", city: A, region: AR, keyword: "solar panel", negotiable: true, delivery: true, condition: "Brand New", desc: "300W monocrystalline solar panel. Great for lights and fridges." },

  // ── Baby & Kids ───────────────────────────────────────────
  { name: "Pampers Diapers (Midi 48s)", brand: "Pampers", price: 320, main: "Baby & Kids", sub: "Diapering", sub2: "Diapers", city: A, region: AR, keyword: "baby diapers", negotiable: false, delivery: true, condition: "Brand New", desc: "Pampers midi size 4, pack of 48. Dry and comfortable." },
  { name: "Cerelac Baby Cereal 900g", brand: "Nestlé", price: 130, main: "Baby & Kids", sub: "Feeding", sub2: "Baby Food & Formulas", city: A, region: AR, keyword: "baby cereal", negotiable: false, delivery: true, condition: "Brand New", desc: "Cerelac wheat baby cereal for 6+ months. Sealed tin." },
  { name: "Baby Stroller", brand: "Chicco", price: 2800, main: "Baby & Kids", sub: "Strollers & Prams", sub2: "Strollers", city: A, region: AR, keyword: "baby stroller", negotiable: true, delivery: true, condition: "Brand New", desc: "Chicco lightweight stroller with canopy and storage basket." },
  { name: "Kids' School Backpack", brand: "Local Brand", price: 180, main: "Baby & Kids", sub: "School & Stationery", sub2: "Backpacks & Bags", city: K, region: KAR, keyword: "school backpack", negotiable: true, delivery: true, condition: "Brand New", desc: "Durable kids' school backpack with padded straps." },
  { name: "Kids' Bicycle 16-inch", brand: "Royal", price: 1200, main: "Baby & Kids", sub: "Bikes & Ride-ons", sub2: "Kids' Bicycles", city: A, region: AR, keyword: "kids bicycle", negotiable: true, delivery: true, condition: "Brand New", desc: "16-inch kids' bicycle with training wheels and basket." },
  { name: "Baby Cotton Onesies (5-pack)", brand: "Local Brand", price: 150, main: "Baby & Kids", sub: "Baby Clothing", sub2: "Onesies & Bodysuits", city: A, region: AR, keyword: "baby clothes", negotiable: true, delivery: true, condition: "Brand New", desc: "5-pack soft cotton onesies for newborns. Machine washable." },

  // ── Toys & Games ──────────────────────────────────────────
  { name: "LEGO Classic Bricks 1100pcs", brand: "LEGO", price: 450, main: "Toys & Games", sub: "Building & Blocks", sub2: "LEGO & Bricks", city: A, region: AR, keyword: "lego bricks", negotiable: true, delivery: true, condition: "Brand New", desc: "LEGO classic brick box. Great for creative building." },
  { name: "Monopoly Board Game", brand: "Hasbro", price: 250, main: "Toys & Games", sub: "Board & Card Games", sub2: "Board Games", city: A, region: AR, keyword: "board game", negotiable: true, delivery: true, condition: "Brand New", desc: "Classic Monopoly board game for family nights." },
  { name: "Barbie Fashion Doll", brand: "Mattel", price: 300, main: "Toys & Games", sub: "Dolls & Playsets", sub2: "Dolls & Dollhouses", city: A, region: AR, keyword: "barbie doll", negotiable: true, delivery: true, condition: "Brand New", desc: "Barbie fashion doll with accessories. Kids love it." },
  { name: "RC Racing Car", brand: "Local Brand", price: 350, main: "Toys & Games", sub: "Remote Control", sub2: "RC Cars & Trucks", city: A, region: AR, keyword: "rc car", negotiable: true, delivery: true, condition: "Brand New", desc: "Remote-control racing car with rechargeable battery." },
  { name: "Soccer Table Game", brand: "Local Brand", price: 900, main: "Toys & Games", sub: "Outdoor Play", sub2: "Sport Toys & Games", city: A, region: AR, keyword: "foosball table", negotiable: true, delivery: true, condition: "Brand New", desc: "Foosball table for home entertainment. Compact and sturdy." },

  // ── Sports & Outdoors ─────────────────────────────────────
  { name: "Dumbbell Set 20kg", brand: "Local Brand", price: 1300, main: "Sports & Outdoors", sub: "Fitness & Gym", sub2: "Weights & Dumbbells", city: A, region: AR, keyword: "dumbbells", negotiable: true, delivery: true, condition: "Brand New", desc: "Adjustable dumbbell set up to 20kg with rack." },
  { name: "Adidas Football (Size 5)", brand: "Adidas", price: 350, main: "Sports & Outdoors", sub: "Football (Soccer)", sub2: "Goals & Accessories", city: A, region: AR, keyword: "football ball", negotiable: true, delivery: true, condition: "Brand New", desc: "Official size 5 football. Suitable for all surfaces." },
  { name: "Yoga Mat with Strap", brand: "Local Brand", price: 250, main: "Sports & Outdoors", sub: "Fitness & Gym", sub2: "Yoga & Pilates", city: A, region: AR, keyword: "yoga mat", negotiable: true, delivery: true, condition: "Brand New", desc: "6mm non-slip yoga mat with carry strap." },
  { name: "Trekking Backpack 60L", brand: "Local Brand", price: 750, main: "Sports & Outdoors", sub: "Camping & Hiking", sub2: "Backpacks & Gear", city: A, region: AR, keyword: "hiking backpack", negotiable: true, delivery: true, condition: "Brand New", desc: "60-litre waterproof trekking backpack with rain cover." },
  { name: "Fishing Rod Combo", brand: "Shimano", price: 1100, main: "Sports & Outdoors", sub: "Fishing", sub2: "Rods & Reels", city: A, region: AR, keyword: "fishing rod", negotiable: true, delivery: true, condition: "Brand New", desc: "Shimano 6ft rod and reel combo. Ready for the coast." },
  { name: "Boxing Gloves 12oz", brand: "Everlast", price: 400, main: "Sports & Outdoors", sub: "Other Sports", sub2: "Boxing & Martial Arts", city: A, region: AR, keyword: "boxing gloves", negotiable: true, delivery: true, condition: "Brand New", desc: "Everlast 12oz boxing gloves with hand wraps." },

  // ── Vehicles ──────────────────────────────────────────────
  { name: "Toyota Corolla 2012", brand: "Toyota", price: 145000, main: "Vehicles", sub: "Cars", sub2: "Sedans", city: A, region: AR, keyword: "toyota corolla", negotiable: true, delivery: false, condition: "Used - Good", desc: "Toyota Corolla 2012, clean title, one owner. Fully serviced." },
  { name: "Toyota Camry 2008", brand: "Toyota", price: 98000, main: "Vehicles", sub: "Cars", sub2: "Sedans", city: A, region: AR, keyword: "toyota camry", negotiable: true, delivery: false, condition: "Used - Good", desc: "Toyota Camry 2008 V6. Well maintained, fresh tyres." },
  { name: "Nissan Almera 2016", brand: "Nissan", price: 82000, main: "Vehicles", sub: "Cars", sub2: "Sedans", city: A, region: AR, keyword: "nissan almera", negotiable: true, delivery: false, condition: "Used - Good", desc: "Nissan Almera 2016, low mileage, fuel efficient." },
  { name: "Hyundai Tucson 2015", brand: "Hyundai", price: 210000, main: "Vehicles", sub: "Cars", sub2: "SUVs & Crossovers", city: A, region: AR, keyword: "hyundai tucson", negotiable: true, delivery: false, condition: "Used - Good", desc: "Hyundai Tucson 2015 automatic. Spacious family SUV." },
  { name: "Toyota Hilux 2016", brand: "Toyota", price: 320000, main: "Vehicles", sub: "Cars", sub2: "Trucks & Pickups", city: A, region: AR, keyword: "toyota hilux", negotiable: true, delivery: false, condition: "Used - Good", desc: "Toyota Hilux 2016 4x4 double cab. Strong engine." },
  { name: "KIA Morning 2019", brand: "KIA", price: 68000, main: "Vehicles", sub: "Cars", sub2: "Hatchbacks", city: A, region: AR, keyword: "kia picanto", negotiable: true, delivery: false, condition: "Used - Good", desc: "KIA Morning 2019 automatic. Perfect first car." },
  { name: "Honda CBR 250R", brand: "Honda", price: 42000, main: "Vehicles", sub: "Motorcycles", sub2: "Motorcycles", city: A, region: AR, keyword: "honda motorcycle", negotiable: true, delivery: false, condition: "Used - Good", desc: "Honda CBR 250R sport bike. Registered, roadworthy." },

  // ── Books, Movies & Music ─────────────────────────────────
  { name: "Kwame Nkrumah Autobiography", brand: "Local Publisher", price: 120, main: "Books, Movies & Music", sub: "Books", sub2: "Non-Fiction", city: A, region: AR, keyword: "book", negotiable: false, delivery: true, condition: "Brand New", desc: "Ghana: The Autobiography of Kwame Nkrumah. Classic read." },
  { name: "A+ Series Core Maths Textbook", brand: "Aki-Ola", price: 180, main: "Books, Movies & Music", sub: "Books", sub2: "Textbooks & Academic", city: A, region: AR, keyword: "textbook", negotiable: false, delivery: true, condition: "Brand New", desc: "A+ Series Core Mathematics for SHS. Complete syllabus." },
  { name: "Children's Bible Storybook", brand: "Local Publisher", price: 150, main: "Books, Movies & Music", sub: "Books", sub2: "Children's Books", city: A, region: AR, keyword: "children's book", negotiable: false, delivery: true, condition: "Brand New", desc: "Illustrated Bible storybook for kids with colour pictures." },
  { name: "Acoustic Guitar", brand: "Yamaha", price: 1500, main: "Books, Movies & Music", sub: "Musical Instruments", sub2: "Guitars & Bass", city: A, region: AR, keyword: "acoustic guitar", negotiable: true, delivery: true, condition: "Used - Like New", desc: "Yamaha acoustic guitar with case and tuner." },
  { name: "DJ Controller", brand: "Pioneer", price: 9000, main: "Books, Movies & Music", sub: "Musical Instruments", sub2: "Studio & DJ Equipment", city: A, region: AR, keyword: "dj controller", negotiable: true, delivery: true, condition: "Brand New", desc: "Pioneer DJ controller with software. Ready for parties." },
  { name: "Talking Drum (Dondo)", brand: "Local Artisan", price: 800, main: "Books, Movies & Music", sub: "Musical Instruments", sub2: "African Instruments", city: K, region: KAR, keyword: "african drum", negotiable: true, delivery: true, condition: "Brand New", desc: "Handcrafted talking drum from the Ashanti Region." },

  // ── Pet Supplies ──────────────────────────────────────────
  { name: "Pedigree Dog Food 10kg", brand: "Pedigree", price: 950, main: "Pet Supplies", sub: "Dogs", sub2: "Dog Food & Treats", city: A, region: AR, keyword: "dog food", negotiable: false, delivery: true, condition: "Brand New", desc: "Pedigree adult dog food, 10kg bag. Balanced nutrition." },
  { name: "Dog Collar & Leash Set", brand: "Local Brand", price: 120, main: "Pet Supplies", sub: "Dogs", sub2: "Collars, Leashes & Accessories", city: A, region: AR, keyword: "dog collar", negotiable: true, delivery: true, condition: "Brand New", desc: "Adjustable nylon dog collar with matching leash." },
  { name: "Cat Litter 10kg", brand: "Local Brand", price: 180, main: "Pet Supplies", sub: "Cats", sub2: "Litter & Litter Boxes", city: A, region: AR, keyword: "cat litter", negotiable: false, delivery: true, condition: "Brand New", desc: "10kg clumping cat litter with odour control." },
  { name: "Large Bird Cage", brand: "Local Brand", price: 650, main: "Pet Supplies", sub: "Birds", sub2: "Cages & Aviaries", city: A, region: AR, keyword: "bird cage", negotiable: true, delivery: true, condition: "Brand New", desc: "Large metal bird cage with perches and feeders." },
  { name: "Day-Old Chicks (10 pcs)", brand: "Local Farm", price: 150, main: "Pet Supplies", sub: "Livestock & Farm", sub2: "Poultry & Fowl", city: K, region: KAR, keyword: "chicks", negotiable: true, delivery: true, condition: "Brand New", desc: "Vaccinated day-old broiler chicks. Delivery available." },

  // ── Food & Beverages ──────────────────────────────────────
  { name: "Gari 1kg", brand: "Local Mill", price: 35, main: "Food & Beverages", sub: "Groceries & Pantry", sub2: "Grains, Rice & Staples", city: A, region: AR, keyword: "gari", negotiable: false, delivery: true, condition: "Brand New", desc: "Freshly milled gari. Perfect for gari soakings and eba." },
  { name: "Dried Shito (500g)", brand: "Local Cook", price: 90, main: "Food & Beverages", sub: "Groceries & Pantry", sub2: "Spices & Cooking Ingredients", city: A, region: AR, keyword: "shito", negotiable: false, delivery: true, condition: "Brand New", desc: "Homemade dried shito with prawns and fish. Hot and tasty." },
  { name: "Milo 500g Tin", brand: "Nestlé", price: 85, main: "Food & Beverages", sub: "Groceries & Pantry", sub2: "Cereals & Breakfast", city: A, region: AR, keyword: "milo", negotiable: false, delivery: true, condition: "Brand New", desc: "Nestlé Milo 500g. Sealed tin." },
  { name: "Sachet Water (50 pack)", brand: "Local Company", price: 25, main: "Food & Beverages", sub: "Beverages", sub2: "Water & Sachet", city: A, region: AR, keyword: "sachet water", negotiable: false, delivery: true, condition: "Brand New", desc: "Clean, sealed sachet water, pack of 50." },
  { name: "Kasapreko Alomo Bitters", brand: "Kasapreko", price: 45, main: "Food & Beverages", sub: "Beverages", sub2: "Soft Drinks & Juices", city: A, region: AR, keyword: "alomo bitters", negotiable: false, delivery: true, condition: "Brand New", desc: "Kasapreko Alomo Bitters 750ml. Made in Ghana." },
  { name: "Frytol Vegetable Oil 1L", brand: "Frytol", price: 80, main: "Food & Beverages", sub: "Groceries & Pantry", sub2: "Canned & Jarred Foods", city: A, region: AR, keyword: "cooking oil", negotiable: false, delivery: true, condition: "Brand New", desc: "Frytol cooking oil 1 litre. Sealed bottle." },
  { name: "Smoked Mackerel (Koobi)", brand: "Local Fisher", price: 120, main: "Food & Beverages", sub: "Groceries & Pantry", sub2: "Canned & Jarred Foods", city: A, region: AR, keyword: "smoked fish", negotiable: true, delivery: true, condition: "Brand New", desc: "Well-smoked mackerel from the coast. Ready for stews." },
  { name: "Indomie Chicken Pack (10)", brand: "Indomie", price: 60, main: "Food & Beverages", sub: "Groceries & Pantry", sub2: "Snacks & Sweets", city: A, region: AR, keyword: "instant noodles", negotiable: false, delivery: true, condition: "Brand New", desc: "Indomie chicken flavour, pack of 10." },
  { name: "Omo Detergent 1kg", brand: "Omo", price: 45, main: "Food & Beverages", sub: "Household Supplies", sub2: "Laundry", city: A, region: AR, keyword: "detergent", negotiable: false, delivery: true, condition: "Brand New", desc: "Omo washing detergent 1kg. Fresh clean smell." },

  // ── Services ──────────────────────────────────────────────
  { name: "Phone Screen Replacement", brand: "Local Technician", price: 400, main: "Services", sub: "Repair Services", sub2: "Phone & Tablet Repairs", city: A, region: AR, keyword: "phone repair", negotiable: true, delivery: true, condition: null, desc: "Professional phone screen replacement. Same-day service." },
  { name: "Wedding Photography Package", brand: "Local Studio", price: 3500, main: "Services", sub: "Events & Weddings", sub2: "Photography & Videography", city: A, region: AR, keyword: "wedding photography", negotiable: true, delivery: true, condition: null, desc: "Full-day wedding photography and videography package." },
  { name: "Dressmaking (Kente Gown)", brand: "Local Tailor", price: 450, main: "Services", sub: "Home & Salon Services", sub2: "Tailoring & Fashion", city: A, region: AR, keyword: "sewing", negotiable: true, delivery: true, condition: null, desc: "Custom kente gown sewing with 3 fittings." },
  { name: "Web Design Package", brand: "Local Agency", price: 2000, main: "Services", sub: "Web & Design", sub2: "Web Development", city: A, region: AR, keyword: "web design", negotiable: true, delivery: true, condition: null, desc: "5-page business website with hosting and training." },
  { name: "Plumbing Repairs", brand: "Local Plumber", price: 150, main: "Services", sub: "Home & Salon Services", sub2: "Plumbing & Electrical", city: A, region: AR, keyword: "plumbing", negotiable: true, delivery: true, condition: null, desc: "Reliable plumbing repairs. Call-out fee applies." },
  { name: "Driving Lessons Package", brand: "Local School", price: 2800, main: "Services", sub: "Lessons & Tutoring", sub2: "Driving Lessons", city: A, region: AR, keyword: "driving school", negotiable: true, delivery: true, condition: null, desc: "12-session driving lessons package including provisional license support." },
  { name: "MTN 5GB Data Bundle", brand: "MTN", price: 120, main: "Services", sub: "Airtime & Data", sub2: "Data Bundles", city: A, region: AR, keyword: "mobile data", negotiable: false, delivery: true, condition: null, desc: "MTN 5GB data bundle delivered instantly to your number." },

  // ── Other ─────────────────────────────────────────────────
  { name: "Gift Voucher (GH₵200)", brand: "Local Store", price: 200, main: "Other", sub: "Other Items", sub2: "Gift Cards & Vouchers", city: A, region: AR, keyword: "gift card", negotiable: false, delivery: true, condition: "Brand New", desc: "Redeemable gift voucher for any item in the store." },
];